# -*- coding: utf-8 -*-
# Lead entry for Miniclô — generated by autonomous cycle 2026-06-24

LEADS = [
    {
        "slug": "miniclo",
        "theme": "dark",
        "empresa": "Miniclô",
        "contato": "Juliano Bonfim Barros",
        "cargo_area": "Indústria de moda bebê / Atacado",
        "local": "Terra Roxa, PR",
        "telefone": "",
        "site": "institucional.miniclo.com.br",
        "sobre": ("A Miniclô é uma indústria de moda bebê 100% nacional, com parque fabril de 1.200 m² em Terra Roxa (PR). "
                  "Atua há mais de 20 anos na produção e venda de peças exclusivas para o mercado atacadista, "
                  "presente em 3.000 pontos de venda (baby shops) em todo o Brasil. Produz 20.000 peças por mês "
                  "e conta com mais de 120 colaboradores diretos e indiretos."),
        "sobre_fonte": "site oficial institucional.miniclo.com.br + dados do diagnóstico Zydon",
        "vende_para": "Lojistas e baby shops de todo o Brasil (atacado B2B)",
        "como_vende": "Representantes e vendedores internos",
        "loja_virtual": "Não",
        "vendedores": "Representantes e vendedores internos",
        "time_total": "21 a 100 (site: +120 colaboradores)",
        "faturamento": "R$ 1 milhão a R$ 5 milhões por ano",
        "compra_sozinho": "Estimativa: lojistas pedem via representante e vendedor interno",
        "self_serve_resp": "",
        "dor": "",
        "encontramos": [
            "Portal B2B onde os 3.000 lojistas consultam catálogo, tabela de preço e fazem pedidos sozinhos, sem depender de representante",
            "Automação do ciclo de pedido recorrente: coleções programadas com aviso de lançamento e reposição automática para lojistas",
            "Integração nativa com Omie para sincronizar estoque da fábrica, pedidos e cadastro de clientes em tempo real"
        ],
        "detalhe": "",
        "conta": ("Com 3.000 pontos de venda atendidos por representantes e vendedores internos, "
                   "cada pedido que chega por WhatsApp ou telefone consome tempo de venda que deveria ser de relacionamento. "
                   "Um portal B2B converte essa recompra de coleções em self-service, liberando a equipe para abrir novos mercados."),
        "pot_low": "R$ 800 mil", "pot_high": "R$ 3 milhões",
        "deixa_mes": "R$ 66 mil a R$ 250 mil",
        "pot_base": "Estimativa baseada em faixa de faturamento R$1-5M e potencial de digitalização do canal de atacado.",
        "significa": ("Um portal B2B self-service para os milhares de lojistas recupera de 10% a 15% do faturamento "
                       "que hoje se perde com retrabalho de pedidos, vendedor ocupado tirando pedido e coleções que não chegam "
                       "no tempo certo ao lojista."),
        "erp": "Omie",
        "erp_integ": "Omie — nativa",
        "erp_golive": "7 a 14 dias",
        "erp_dev": "Não (nativo)",
        "erp_line": ("A Zydon tem integração nativa com Sankhya, Omie, Olist e Bling — go-live mais rápido, "
                      "sem projeto customizado. ERPs diferentes são suportados sob avaliação."),
        "pushpull": ("Operação empurra coleção para o lojista via representante — digitalizar o pedido recorrente "
                      "sem perder o relacionamento comercial é o ponto de alavancagem."),
    },
]
