# -*- coding: utf-8 -*-
# Dados dos leads para o motor de PDFs — baseado no padrão do Rafael

LEADS = [
    {
        "slug": "glassway",
        "theme": "dark",
        "empresa": "Glassway",
        "contato": "Fabio",
        "cargo_area": "Segurança eletrônica / Monitoramento",
        "local": "São Paulo, SP",
        "telefone": "",
        "site": "glassway.com.br",
        "sobre": ("A Glassway é uma empresa de segurança eletrônica e monitoramento 24h, sediada em São Paulo. "
                  "Opera com contratos recorrentes de monitoramento, instalação e manutenção de sistemas de alarme "
                  "e câmeras para clientes comerciais e residenciais."),
        "sobre_fonte": "site oficial glassway.com.br + dados do diagnóstico Zydon",
        "vende_para": "Empresas comerciais e residenciais de São Paulo e região metropolitana (B2B leve)",
        "como_vende": "Contratos recorrentes de monitoramento + venda de equipamentos",
        "loja_virtual": "Não informado",
        "vendedores": "3 a 5 internos",
        "time_total": "10 a 20 pessoas",
        "faturamento": "R$ 500 mil a R$ 1 mi por ano",
        "compra_sozinho": "A confirmar",
        "self_serve_resp": "",
        "dor": "",
        "encontramos": [
            "Catálogo digitalizável de planos de monitoramento por tipo de cliente (comercial, residencial)",
            "Self-service de gestão de contratos, renovação automática e emissão de boletos",
            "Integração com ERPs de segurança para sincronizar clientes, equipamentos e status de manutenção"
        ],
        "detalhe": "",
        "conta": ("Quando a renovação de contrato depende do contato manual, o cancelamento (churn) é alto. "
                   "Um portal B2B com auto-renovação e self-service reduz o cancelamento e aumenta o LTV."),
        "pot_low": "R$ 60 mil", "pot_high": "R$ 150 mil",
        "deixa_mes": "R$ 5 mil a R$ 12,5 mil",
        "pot_base": "Estimativa preliminar baseada em faixa de faturamento e taxa de churn do setor.",
        "significa": ("Um portal B2B com auto-renovação e gestão digital de contratos recupera de 8% a 12% "
                       "do faturamento que hoje se perde com cancelamentos e retrabalho administrativo."),
        "erp": "Não informado",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A integração será construída sob medida para o ERP desta operação. Prazo médio: 30 a 60 dias."),
        "pushpull": ("Modelo de venda depende de contratos recorrentes — digitalizar sem perder o relacionamento pessoal."),
    },
    {
        "slug": "marck-suprimentos",
        "theme": "dark",
        "empresa": "Marck Suprimentos",
        "contato": "Andre",
        "cargo_area": "Suprimentos industriais / Offshore",
        "local": "Rio de Janeiro, RJ",
        "telefone": "",
        "site": "marcksuprimentos.com.br",
        "sobre": ("Marck Suprimentos é uma distribuidora de suprimentos industriais e offshore, atendendo grandes "
                  "operadoras de óleo & gás, indústrias e hospitais. Opera com alto volume de pedidos repetitivos "
                  "(reposição de estoque) e modelo de venda consultiva."),
        "sobre_fonte": "site oficial marcksuprimentos.com.br + dados do diagnóstico Zydon",
        "vende_para": "Grandes operadoras offshore, indústrias e hospitais (B2B)",
        "como_vende": "Venda consultiva + pedidos recorrentes por e-mail/telefone",
        "loja_virtual": "Não informado",
        "vendedores": "5 a 10 internos",
        "time_total": "20 a 50 pessoas",
        "faturamento": "R$ 10 mi a R$ 50 mi por ano",
        "compra_sozinho": "A confirmar",
        "self_serve_resp": "",
        "dor": "",
        "encontramos": [
            "Catálogo digital com preço por volume e desconto por frequência de compra",
            "Integração com ERP de estoque para gerar pedidos automáticos de reposição",
            "Self-service de status de entrega e rastreamento de pedidos offshore"
        ],
        "detalhe": "",
        "conta": ("Cada pedido que chega por e-mail/telefone consome 30 a 45 minutos de um vendedor. "
                   "Com 200 pedidos/mês, são 100 a 150 horas de trabalho que viram autoatendimento num portal."),
        "pot_low": "R$ 1 mi", "pot_high": "R$ 5 mi",
        "deixa_mes": "R$ 83 mil a R$ 416 mil",
        "pot_base": "Estimativa baseada em economia de 15% a 20% do tempo da equipe comercial + redução de erros.",
        "significa": ("Economia de horas da equipe comercial + redução de erros de digitação. "
                       "O valor real depende do volume de pedidos recorrentes e do mix de produtos."),
        "erp": "Não informado",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A integração será construída sob medida para o ERP desta operação. Prazo médio: 30 a 60 dias."),
        "pushpull": ("Setor offshore tem regras de documentação específicas — o portal deve contemplar controle de certificados."),
    },
    {
        "slug": "dental-ita",
        "theme": "dark",
        "empresa": "Dental Ita",
        "contato": "Fernando Vicente",
        "cargo_area": "Distribuição de produtos odontológicos",
        "local": "Santo André, SP",
        "telefone": "",
        "site": "dentalita.com.br",
        "sobre": ("Dental Ita é uma distribuidora de produtos odontológicos com sede em Santo André/SP. "
                  "Representa marcas como Kuraray e Dentsply Sirona, atendendo clínicas e laboratórios "
                  "odontológicos com entrega rápida na região."),
        "sobre_fonte": "site oficial dentalita.com.br + dados do diagnóstico Zydon",
        "vende_para": "Clínicas odontológicas e laboratórios (B2B especializado)",
        "como_vende": "Venda representada + pedidos por e-mail/telefone",
        "loja_virtual": "Não informado",
        "vendedores": "3 a 5 internos",
        "time_total": "10 a 20 pessoas",
        "faturamento": "R$ 2 mi a R$ 10 mi por ano",
        "compra_sozinho": "A confirmar",
        "self_serve_resp": "",
        "dor": "",
        "encontramos": [
            "Catálogo digital por procedimento/marca com preço por volume",
            "Checkout B2B + faturamento automático para clínicas recorrentes",
            "Rastreabilidade de lote e aviso de reposição automática para produtos de alto giro"
        ],
        "detalhe": "",
        "conta": ("Clínicas odontológicas compram toda semana os mesmos consumíveis. Um portal B2B com pedido "
                   "automático e aviso de reposição converte essa recompra espontânea em receita recorrente previsível."),
        "pot_low": "R$ 200 mil", "pot_high": "R$ 1 mi",
        "deixa_mes": "R$ 17 mil a R$ 83 mil",
        "pot_base": "Estimativa baseada em aumento de 15% a 25% na recompra digital.",
        "significa": ("Aumento de recompra digital. O valor real depende da base de clientes ativos e da frequência "
                       "de compra por clínica."),
        "erp": "Não informado",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A integração será construída sob medida para o ERP desta operação. Prazo médio: 30 a 60 dias."),
        "pushpull": ("Produtos odontológicos têm controle de lote e validade — o portal deve alertar sobre vencimentos."),
    },
    {
        "slug": "escard",
        "theme": "dark",
        "empresa": "Escard",
        "contato": "Roberto Cassiano",
        "cargo_area": "Cartões personalizados / Brindes corporativos",
        "local": "São Paulo, SP",
        "telefone": "",
        "site": "escard.com.br",
        "sobre": ("Escard é uma fabricante de cartões personalizados e brindes corporativos, atendendo empresas "
                  "de todos os portes para ações de marketing interno e externo. Opera com produção sob demanda "
                  "e modelo de venda por projeto."),
        "sobre_fonte": "site oficial escard.com.br + dados do diagnóstico Zydon",
        "vende_para": "Empresas de todos os portes para brindes e cartões personalizados (B2B)",
        "como_vende": "Projeto sob demanda + orçamento personalizado",
        "loja_virtual": "Não informado",
        "vendedores": "2 a 5 internos",
        "time_total": "10 a 20 pessoas",
        "faturamento": "R$ 500 mil a R$ 2 mi por ano",
        "compra_sozinho": "A confirmar",
        "self_serve_resp": "",
        "dor": "",
        "encontramos": [
            "Portal com upload de arte e aprovação digital antes da produção",
            "Integração ERP para faturamento recorrente de clientes fixos",
            "Self-service de status de produção e entrega por projeto"
        ],
        "detalhe": "",
        "conta": ("Orçamentos de cartões personalizados demoram de 2 a 4h entre especificação, aprovação e emissão. "
                   "Um portal com pré-cadastro de marcas e templates reduz esse tempo para minutos."),
        "pot_low": "R$ 50 mil", "pot_high": "R$ 200 mil",
        "deixa_mes": "R$ 4 mil a R$ 17 mil",
        "pot_base": "Estimativa baseada em redução de 60% a 80% no tempo de orçamento + aumento de 20% na conversão.",
        "significa": ("Redução do tempo de orçamento + aumento da conversão. "
                       "O valor real depende da complexidade dos projetos e da recorrência de clientes."),
        "erp": "Não informado",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A integração será construída sob medida para o ERP desta operação. Prazo médio: 30 a 60 dias."),
        "pushpull": ("Cada pedido tem especificação diferente — o portal deve permitir upload de arquivos e aprovação visual."),
    },
    {
        "slug": "alleanza-engenharia",
        "theme": "dark",
        "empresa": "Alleanza Engenharia",
        "contato": "Giuliana",
        "cargo_area": "Engenharia ambiental / Licenciamento",
        "local": "São Paulo, SP",
        "telefone": "",
        "site": "alleanza.com.br",
        "sobre": ("Alleanza Engenharia é uma empresa de engenharia ambiental especializada em licenciamento ambiental "
                  "e gestão de áreas contaminadas. Atua como consultora para indústrias e grandes empreendimentos, "
                  "com foco em conformidade regulatória."),
        "sobre_fonte": "site oficial alleanza.com.br + dados do diagnóstico Zydon",
        "vende_para": "Indústrias e grandes empreendimentos (B2B consultivo)",
        "como_vende": "Projeto de consultoria + contrato por escopo",
        "loja_virtual": "Não informado",
        "vendedores": "2 a 5 internos",
        "time_total": "10 a 30 pessoas",
        "faturamento": "R$ 1 mi a R$ 5 mi por ano",
        "compra_sozinho": "A confirmar",
        "self_serve_resp": "",
        "dor": "",
        "encontramos": [
            "Portal de acompanhamento de projetos com milestones e documentos compartilhados",
            "Integração com ERPs de construção para alimentar orçamentos e cronogramas",
            "Self-service de download de laudos, licenças e certificados de conclusão"
        ],
        "detalhe": "",
        "conta": ("Consultorias de engenharia cobram por hora/projeto. Um portal de gestão de projetos aumenta "
                   "a transparência para o cliente e reduz o tempo de aprovação interna, liberando horas de consultoria "
                   "para novos contratos."),
        "pot_low": "R$ 100 mil", "pot_high": "R$ 250 mil",
        "deixa_mes": "R$ 8 mil a R$ 21 mil",
        "pot_base": "Estimativa baseada em ganho de 10% a 15% na alocação de horas de consultoria + redução de retrabalho.",
        "significa": ("Ganho de horas de consultoria + redução de retrabalho administrativo. "
                       "O valor real depende da complexidade dos projetos."),
        "erp": "Não informado",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A integração será construída sob medida para o ERP desta operação. Prazo médio: 30 a 60 dias."),
        "pushpull": ("Serviços de engenharia tem prazos regulatórios fixos — o portal deve alertar sobre vencimentos."),
    },
    {
        "slug": "oeste-shopp",
        "theme": "dark",
        "empresa": "Oeste Shopp",
        "contato": "Douglas",
        "cargo_area": "Gestão de shopping center",
        "local": "São Paulo, SP",
        "telefone": "",
        "site": "oesteshopp.com.br",
        "sobre": ("Oeste Shopp é um shopping center localizado na zona oeste de São Paulo, com gestão de múltiplos "
                  "lojistas. A administração lida com cobranças, emissão de boletos, comunicação de eventos e "
                  "gestão de inadimplência."),
        "sobre_fonte": "site oficial oesteshopp.com.br + dados do diagnóstico Zydon",
        "vende_para": "Lojistas do shopping center (B2B / multi-tenant)",
        "como_vende": "Gestão condominial + cobrança recorrente de aluguel/condomínio",
        "loja_virtual": "Não informado",
        "vendedores": "2 a 5 internos",
        "time_total": "10 a 30 pessoas",
        "faturamento": "R$ 2 mi a R$ 10 mi por ano",
        "compra_sozinho": "A confirmar",
        "self_serve_resp": "",
        "dor": "",
        "encontramos": [
            "Portal do lojista para download de boletos, demonstrativos e comunicados",
            "Self-service de atualização cadastral e emissão de segunda via",
            "Integração com sistema de cobrança para reduzir inadimplência"
        ],
        "detalhe": "",
        "conta": ("Cada lojista que liga para pedir segunda via ou demonstrativo consome 15 a 20 minutos da administração. "
                   "Um portal self-service reduz esse custo em até 80%."),
        "pot_low": "R$ 150 mil", "pot_high": "R$ 500 mil",
        "deixa_mes": "R$ 12,5 mil a R$ 42 mil",
        "pot_base": "Estimativa baseada em economia de horas da equipe administrativa + redução de inadimplência.",
        "significa": ("Economia de horas administrativas + redução de inadimplência por falta de acesso a boletos. "
                       "O valor real depende do número de lojistas."),
        "erp": "Não informado",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A integração será construída sob medida para o ERP desta operação. Prazo médio: 30 a 60 dias."),
        "pushpull": ("Gestão de shopping tem múltiplos lojistas com diferentes contratos — o portal deve suportar múltiplos perfis."),
    },
    {
        "slug": "kioskone",
        "theme": "dark",
        "empresa": "Kioskone (Kiosk One)",
        "contato": "Cayo",
        "cargo_area": "Estandes / kiosques para feiras e eventos",
        "local": "São Paulo, SP",
        "telefone": "",
        "site": "kioskone.com.br",
        "sobre": ("A Kioskone (Kiosk One) é uma empresa especializada na fabricação e locação de estandes profissionais "
                  "para feiras e eventos, com modelo de negócio 'chave na mão', do projeto à montagem. Atende clientes "
                  "de todo o Brasil com foco em agilidade, design e cumprimento de prazos."),
        "sobre_fonte": "site oficial kioskone.com.br + dados do diagnóstico Zydon",
        "vende_para": "Empresas de todo o Brasil para feiras e eventos (B2B)",
        "como_vende": "Projeto + locação por evento",
        "loja_virtual": "Não informado",
        "vendedores": "5 a 10 internos",
        "time_total": "20 a 50 pessoas",
        "faturamento": "R$ 1 mi a R$ 5 mi por ano",
        "compra_sozinho": "A confirmar",
        "self_serve_resp": "",
        "dor": "",
        "encontramos": [
            "Catálogo digital de projetos de estandes por tipo de feira (comercial, industrial, médico)",
            "Integração com checkout B2B para locação recorrente de eventos",
            "Self-service de acompanhamento de projeto, produção e montagem para clientes"
        ],
        "detalhe": "",
        "conta": ("Orçamentos de estandes demoram de 3 a 5 dias entre projeto, aprovação e negociação comercial. "
                   "Um portal com templates por tipo de feira e aprovação digital reduz esse ciclo para horas."),
        "pot_low": "R$ 100 mil", "pot_high": "R$ 250 mil",
        "deixa_mes": "R$ 8 mil a R$ 21 mil",
        "pot_base": "Estimativa baseada em aumento de 20% a 30% na taxa de conversão de orçamentos + redução de 50% no tempo de fechamento.",
        "significa": ("Aumento na conversão de orçamentos + redução do tempo de fechamento. "
                       "O valor real depende da recorrência de clientes e do ticket médio."),
        "erp": "Não informado",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A integração será construída sob medida para o ERP desta operação. Prazo médio: 30 a 60 dias."),
        "pushpull": ("Cada evento tem prazo fixo — o portal deve alertar sobre datas de montagem, desmontagem e aprovação."),
    },
    {
        "slug": "arumia-house",
        "theme": "dark",
        "empresa": "Arumia House",
        "contato": "",
        "cargo_area": "Móveis planejados / Decoração",
        "local": "Brasil",
        "telefone": "",
        "site": "",
        "sobre": ("Arumia House é uma empresa de móveis planejados e decoração, atendendo clientes residenciais e "
                  "comerciais com projetos personalizados. Opera com modelo de projeto sob demanda e venda de móveis "
                  "de alto padrão."),
        "sobre_fonte": "dados do diagnóstico Zydon",
        "vende_para": "Clientes residenciais e comerciais (B2C/B2B leve)",
        "como_vende": "Projeto sob demanda + showroom",
        "loja_virtual": "Não informado",
        "vendedores": "2 a 5 internos",
        "time_total": "10 a 20 pessoas",
        "faturamento": "R$ 500 mil a R$ 2 mi por ano",
        "compra_sozinho": "A confirmar",
        "self_serve_resp": "",
        "dor": "",
        "encontramos": [
            "Catálogo digital por ambiente (quarto, sala, cozinha, escritório)",
            "Integração ERP para projetos personalizados e controle de produção",
            "Self-service de status de projeto e entrega para clientes"
        ],
        "detalhe": "",
        "conta": ("Projetos de móveis planejados demoram de 15 a 30 dias entre medição, aprovação e produção. "
                   "Um portal com pré-definições por ambiente reduz esse ciclo."),
        "pot_low": "R$ 50 mil", "pot_high": "R$ 200 mil",
        "deixa_mes": "R$ 4 mil a R$ 17 mil",
        "pot_base": "Estimativa baseada em redução de 30% no tempo de fechamento + aumento de 15% na conversão.",
        "significa": ("Redução do ciclo de venda + aumento da conversão. "
                       "O valor real depende da complexidade dos projetos e da recorrência."),
        "erp": "Não informado",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A integração será construída sob medida para o ERP desta operação. Prazo médio: 30 a 60 dias."),
        "pushpull": ("Móveis planejados são compostos por projetos únicos — o portal deve permitir pré-definições e aprovação visual."),
    },
    {
        "slug": "atacadistaonline",
        "theme": "dark",
        "empresa": "Atacadista Online",
        "contato": "",
        "cargo_area": "Atacado / Distribuição digital",
        "local": "Brasil",
        "telefone": "",
        "site": "",
        "sobre": ("Atacadista Online é uma operação de atacado digital, atendendo lojistas e pequenos varejistas "
                  "com catálogo online e entrega em todo o Brasil. Opera com modelo de venda recorrente e "
                  "preço por volume."),
        "sobre_fonte": "dados do diagnóstico Zydon",
        "vende_para": "Lojistas e pequenos varejistas (B2B)",
        "como_vende": "E-commerce B2B + app",
        "loja_virtual": "Sim",
        "vendedores": "3 a 5 internos",
        "time_total": "10 a 20 pessoas",
        "faturamento": "R$ 2 mi a R$ 10 mi por ano",
        "compra_sozinho": "Sim",
        "self_serve_resp": "sim",
        "dor": "",
        "encontramos": [
            "Catálogo digital com preço por volume e desconto por frequência de compra",
            "Integração ERP para sincronizar estoque, tabela e pedidos em tempo real",
            "Self-service de acompanhamento de pedidos e status de entrega"
        ],
        "detalhe": "",
        "conta": ("Lojistas que compram por volume precisam de preço exclusivo e prazo de entrega confiável. "
                   "Um portal B2B com tabela por cliente e histórico de pedidos aumenta a recorrência."),
        "pot_low": "R$ 200 mil", "pot_high": "R$ 1 mi",
        "deixa_mes": "R$ 17 mil a R$ 83 mil",
        "pot_base": "Estimativa baseada em aumento de 10% a 15% na recorrência de compra + redução de erros de tabela.",
        "significa": ("Aumento da recorrência + redução de erros operacionais. "
                       "O valor real depende da base de clientes ativos e do ticket médio."),
        "erp": "Não informado",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A integração será construída sob medida para o ERP desta operação. Prazo médio: 30 a 60 dias."),
        "pushpull": ("Operação puxada pelo cliente que repõe sozinho = maior potencial de recompra"),
    },
    {
        "slug": "clima-sub",
        "theme": "dark",
        "empresa": "Clima Sub",
        "contato": "",
        "cargo_area": "Climatização / HVAC",
        "local": "Brasil",
        "telefone": "",
        "site": "",
        "sobre": ("Clima Sub é uma distribuidora de equipamentos de climatização (HVAC), atendindo indústrias e "
                  "empresas com insumos para ar-condicionado, ventilação e refrigeração. Opera com pedidos "
                  "recorrentes de reposição de estoque."),
        "sobre_fonte": "dados do diagnóstico Zydon",
        "vende_para": "Indústrias e empresas (B2B)",
        "como_vende": "Venda técnica + pedidos por e-mail/telefone",
        "loja_virtual": "Não informado",
        "vendedores": "3 a 5 internos",
        "time_total": "10 a 20 pessoas",
        "faturamento": "R$ 1 mi a R$ 5 mi por ano",
        "compra_sozinho": "A confirmar",
        "self_serve_resp": "",
        "dor": "",
        "encontramos": [
            "Catálogo digital por categoria (ar-condicionado, ventilação, refrigeração)",
            "Integração ERP para pedidos automáticos de reposição",
            "Self-service de status de entrega e rastreamento"
        ],
        "detalhe": "",
        "conta": ("Indústrias precisam repor insumos de climatização periodicamente. Um portal B2B com pedido "
                   "automático e aviso de reposição converte essa recompra em receita previsível."),
        "pot_low": "R$ 100 mil", "pot_high": "R$ 500 mil",
        "deixa_mes": "R$ 8 mil a R$ 42 mil",
        "pot_base": "Estimativa baseada em aumento de 10% a 15% na recompra digital.",
        "significa": ("Aumento da recompra digital. O valor real depende da base de clientes ativos e da frequência "
                       "de compra por cliente."),
        "erp": "Não informado",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A integração será construída sob medida para o ERP desta operação. Prazo médio: 30 a 60 dias."),
        "pushpull": ("Pedidos recorrentes de insumos — o portal deve alertar sobre estoque mínimo e prazos de entrega."),
    },
    {
        "slug": "neogrid",
        "theme": "dark",
        "empresa": "Neogrid",
        "contato": "Robson",
        "cargo_area": "Tecnologia / Supply chain (gestão da cadeia de suprimentos)",
        "local": "São Paulo, SP",
        "telefone": "",
        "site": "neogrid.com",
        "sobre": ("A Neogrid é uma empresa brasileira de tecnologia (SaaS) líder em gestão automática da cadeia de "
                  "suprimentos, fundada em 1999 por Miguel Abuhab (fundador da Datasul), com sede em Joinville/SC e "
                  "operações em São Paulo e no exterior. Conecta o ecossistema de bens de consumo — mais de 37 mil "
                  "indústrias, ~5 mil distribuidores e centenas de redes varejistas (BRF, PepsiCo, Coca-Cola, "
                  "Carrefour, Casas Bahia) — sincronizando estoque, vendas e reposição com base no consumo real. "
                  "É listada na B3 (NGRD3), no setor de Tecnologia da Informação."),
        "sobre_fonte": "Fontes: neogrid.com/quem-somos, Vai Investir (NGRD3) e relatório de resultados 2024 (Visno Invest/SpaceMoney) — cruzados com o diagnóstico comercial Zydon.",
        "vende_para": "Indústrias de bens de consumo, distribuidores e grandes redes varejistas — ecossistema B2B com +37 mil indústrias e centenas de redes conectadas",
        "como_vende": "Loja física / operação comercial direta",
        "loja_virtual": "Não possui",
        "vendedores": "Não informado",
        "time_total": "Mais de 150 pessoas",
        "faturamento": "Acima de R$ 500 milhões por ano",
        "compra_sozinho": "A confirmar",
        "self_serve_resp": "",
        "dor": "",
        "encontramos": [
            "Ecossistema B2B gigante — milhares de indústrias, distribuidores e redes conectados — mas boa parte da contratação e renovação ainda passa pelo time comercial direto",
            "Receita majoritariamente recorrente (assinaturas/serviços): contratação, upgrade e renovação são repetitivos e previsíveis — o cenário ideal para autoatendimento digital",
            "Sem canal digital próprio para o cliente contratar, expandir ou renovar serviços sozinho: cada movimentação depende de vendedor"
        ],
        "detalhe": "",
        "conta": ("A Neogrid vive de receita recorrente vinda de milhares de contratos B2B. Cada renovação, upgrade "
                  "ou nova contratação que ainda depende de um vendedor é tempo de equipe consumido em algo que poderia "
                  "ser autoatendimento — e cada renovação que escapa por fricção vira churn."),
        "pot_low": "R$ 8 milhões", "pot_high": "R$ 25 milhões",
        "deixa_mes": "R$ 666 mil a R$ 2,1 milhões",
        "pot_base": ("1,6% a 5% sobre um faturamento acima de R$ 500 milhões/ano — faixa de receita recorrente B2B "
                     "tipicamente recuperável com um canal digital de autoatendimento (contratação, upgrade e renovação) "
                     "e redução de churn."),
        "significa": ("Um portal B2B de autoatendimento para contratação, upgrade e renovação recupera a parcela da "
                      "receita recorrente que hoje se perde em fricção comercial e cancelamentos — algo entre 1,6% e 5% "
                      "do faturamento."),
        "erp": "TOTVS",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A Zydon avalia a integração com TOTVS sob projeto técnico. Prazo médio: 30 a 60 dias para go-live. "
                     "ERPs nativos Zydon: Sankhya, Omie, Olist e Bling."),
        "pushpull": ("Operação de receita recorrente: a demanda já é puxada (renovações e expansões acontecem o tempo "
                     "todo), mas a contratação ainda é empurrada pelo vendedor. Um portal de autoatendimento transforma "
                     "renovação e upgrade em fluxo puxado pelo próprio cliente."),
        "food": False,
    },
    {
        "slug": "rank-rank-com-rcio-ltda",
        "theme": "dark",
        "empresa": "Rank Rank Comércio ltda",
        "contato": "",
        "cargo_area": "Comércio geral",
        "local": "Brasil",
        "telefone": "",
        "site": "",
        "sobre": ("Rank Rank Comércio ltda é uma empresa de comércio geral, atendendo clientes com produtos "
                  "diversificados. Opera com modelo de venda recorrente e entrega para todo o Brasil."),
        "sobre_fonte": "dados do diagnóstico Zydon",
        "vende_para": "Clientes de comércio geral (B2B)",
        "como_vende": "Venda recorrente + e-commerce",
        "loja_virtual": "Não informado",
        "vendedores": "2 a 5 internos",
        "time_total": "10 a 20 pessoas",
        "faturamento": "R$ 500 mil a R$ 2 mi por ano",
        "compra_sozinho": "A confirmar",
        "self_serve_resp": "",
        "dor": "",
        "encontramos": [
            "Catálogo digital com produtos diversificados",
            "Integração ERP para gestão de estoque e pedidos",
            "Self-service de acompanhamento de pedidos e status de entrega"
        ],
        "detalhe": "",
        "conta": ("Comércio geral com múltiplos produtos precisa de organização de catálogo e preço. "
                   "Um portal B2B com tabela por cliente aumenta a recorrência."),
        "pot_low": "R$ 50 mil", "pot_high": "R$ 200 mil",
        "deixa_mes": "R$ 4 mil a R$ 17 mil",
        "pot_base": "Estimativa baseada em aumento de 10% a 15% na recorrência de compra.",
        "significa": ("Aumento da recorrência + redução de erros operacionais. "
                       "O valor real depende da base de clientes e do mix de produtos."),
        "erp": "Não informado",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A integração será construída sob medida para o ERP desta operação. Prazo médio: 30 a 60 dias."),
        "pushpull": ("Comércio geral com múltiplos produtos — o portal deve organizar catálogo e preço por cliente."),
    },
    {
        "slug": "s-o-paulo",
        "theme": "dark",
        "empresa": "São Paulo Distribuidora",
        "contato": "Mauricio",
        "cargo_area": "Distribuição geral",
        "local": "São Paulo, SP",
        "telefone": "",
        "site": "",
        "sobre": ("Distribuidora geral na região de São Paulo, atendendo lojistas e pequenos varejistas com "
                  "produtos diversificados. Opera com modelo de venda recorrente e entrega rápida."),
        "sobre_fonte": "dados do diagnóstico Zydon",
        "vende_para": "Lojistas e pequenos varejistas (B2B)",
        "como_vende": "Venda externa + pedidos por e-mail/telefone",
        "loja_virtual": "Não informado",
        "vendedores": "3 a 5 internos",
        "time_total": "10 a 20 pessoas",
        "faturamento": "R$ 500 mil a R$ 2 mi por ano",
        "compra_sozinho": "A confirmar",
        "self_serve_resp": "",
        "dor": "",
        "encontramos": [
            "Catálogo digital regional com produtos diversificados",
            "Integração ERP para gestão de vendas e estoque",
            "Self-service de status de entrega e pedidos"
        ],
        "detalhe": "",
        "conta": ("Distribuidor regional com múltiplos lojistas precisa de agilidade no pedido e na entrega. "
                   "Um portal B2B reduz o tempo de atendimento."),
        "pot_low": "R$ 50 mil", "pot_high": "R$ 200 mil",
        "deixa_mes": "R$ 4 mil a R$ 17 mil",
        "pot_base": "Estimativa baseada em redução de tempo de atendimento + aumento de recorrência.",
        "significa": ("Redução do tempo de atendimento + aumento da recorrência. "
                       "O valor real depende da base de clientes e do ticket médio."),
        "erp": "Não informado",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A integração será construída sob medida para o ERP desta operação. Prazo médio: 30 a 60 dias."),
        "pushpull": ("Distribuição regional — o portal deve organizar pedidos por região e otimizar rotas de entrega."),
    },
    {
        "slug": "santim",
        "theme": "dark",
        "empresa": "Santim",
        "contato": "",
        "cargo_area": "Representação comercial",
        "local": "Brasil",
        "telefone": "",
        "site": "",
        "sobre": ("Santim é uma empresa de representação comercial, atendendo indústrias e distribuidores com "
                  "força de vendas terceirizada. Opera com modelos de venda consultiva e recorrência de pedidos."),
        "sobre_fonte": "dados do diagnóstico Zydon",
        "vende_para": "Indústrias e distribuidores (B2B)",
        "como_vende": "Representação comercial + venda consultiva",
        "loja_virtual": "Não informado",
        "vendedores": "2 a 5 internos",
        "time_total": "10 a 20 pessoas",
        "faturamento": "R$ 500 mil a R$ 2 mi por ano",
        "compra_sozinho": "A confirmar",
        "self_serve_resp": "",
        "dor": "",
        "encontramos": [
            "Portal de pedidos online para representados",
            "Integração ERP para gestão de carteira de clientes",
            "Self-service de acompanhamento de pedidos e status"
        ],
        "detalhe": "",
        "conta": ("Representantes comerciais dependem de tempo para visitar clientes. Um portal B2B com pedido "
                   "online e autoatendimento libera o representante para fechar novos negócios."),
        "pot_low": "R$ 50 mil", "pot_high": "R$ 200 mil",
        "deixa_mes": "R$ 4 mil a R$ 17 mil",
        "pot_base": "Estimativa baseada em liberação de tempo do representante para novos negócios + aumento de recorrência.",
        "significa": ("Liberação de tempo do representante + aumento de recorrência. "
                       "O valor real depende do tamanho da carteira de clientes."),
        "erp": "Não informado",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A integração será construída sob medida para o ERP desta operação. Prazo médio: 30 a 60 dias."),
        "pushpull": ("Representação comercial — o portal deve permitir pedido rápido e acompanhamento de carteira."),
    },
    {
        "slug": "plasticos-piracicaba",
        "theme": "dark",
        "empresa": "PLÁSTICOS PIRACICABA",
        "contato": "Ricardo",
        "cargo_area": "Confecções e moda",
        "local": "Brasil",
        "telefone": "",
        "site": "",
        "sobre": ("A Plásticos Piracicaba é uma operação em início de tração, com time enxuto e foco em distribuição B2B. "
                  "A empresa nasce conectada ao potencial do comércio entre confecções e um modelo onde o cliente final compra sozinho, "
                  "o que aponta para uma operação de demanda puxada."),
        "sobre_fonte": "Pesquisa web e respostas do diagnóstico comercial Zydon.",
        "vende_para": "Confecções",
        "como_vende": "Atualmente sem modelo definido — operação em início de tração",
        "loja_virtual": "Não",
        "vendedores": "1",
        "time_total": "1 a 10",
        "faturamento": "Ainda não faturamos",
        "compra_sozinho": "Sim",
        "self_serve_resp": "",
        "dor": "",
        "encontramos": [
            "Operação em início de tração, sem faturamento formal ainda",
            "Cliente final declarou que compraria sozinho — demanda puxada",
            "ERP não padronizado; integração será mapeada no projeto"
        ],
        "detalhe": "",
        "conta": ("Quem depende do vendedor para cada pedido tem o teto na capacidade da equipe. "
                  "Aqui, como o cliente compra sozinho, o teto vira a experiência do portal e a disponibilidade do catálogo."),
        "pot_low": "R$ 50 mil", "pot_high": "R$ 250 mil",
        "deixa_mes": "R$ 4 mil a R$ 20 mil por mês",
        "pot_base": "Estimativa baseada em operação inicial de distribuição B2B, a confirmar com faturamento real.",
        "significa": ("A Plásticos Piracicaba está no perfil que mais se beneficia de um portal B2B com autoatendimento: "
                       "a demanda já existe, falta apenas o canal digital para capturá-la."),
        "erp": "Outro",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A integração será construída sob medida para o ERP desta operação. Prazo médio: 30 a 60 dias."),
        "pushpull": ("Operação com perfil puxado: o cliente JÁ compra sozinho. Basta estruturar o canal digital para capturar essa demanda."),
    },
    {
        "slug": "sharp",
        "nome": "Guilherme Bim",
        "empresa": "Sharp",
        "contato": "Guilherme Bim",
        "site": "https://sharpmetal.com.br",
        "cargo_area": "Diretor / Metalúrgica",
        "local": "Brasil",
        "story": ("A Sharp começou como uma operação metalúrgica enxuta e hoje comercializa pela internet para o mercado B2B de metal. "
                   "Com estrutura reduzida e foco em processos digitais, a empresa demonstra perfil de negócio que quer escalar vendas online, "
                   "mas ainda depende do WhatsApp e do vendedor para fechar pedidos."),
        "class": "Metal / B2B",
        "theme": "dark",
        "sobre": ("A Sharp é uma operação metalúrgica B2B enxuta, que comercializa pela internet e atua no segmento de metal. "
                  "Com estrutura reduzida (até 10 pessoas, 1 vendedor), a empresa já usa o WhatsApp como canal principal de venda e "
                  "possui uma loja virtual. Essa combinação mostra um negócio que quer crescer no digital, mas ainda depende de processos manuais."),
        "sobre_fonte": "Dados do diagnóstico e pesquisa de domínio.",
        "vende_para": "B2B / metal",
        "como_vende": "WhatsApp",
        "loja_virtual": "Sim",
        "vendedores": "1",
        "time_total": "1 a 10",
        "faturamento": "R$ 500 mil a R$ 1 milhão",
        "compra_sozinho": "Sim",
        "self_serve_resp": "",
        "dor": "Pedidos chegam desorganizados (WhatsApp, telefone, planilha)",
        "encontramos": [
            "Vende B2B no segmento de metal com faturamento entre R$ 500 mil e R$ 1 milhão",
            "Já usa loja virtual e WhatsApp como canal principal",
            "Cliente final declarou que compraria sozinho — demanda puxada",
            "ERP não padronizado (Outro); integração será mapeada no projeto"
        ],
        "detalhe": "",
        "conta": ("Quem depende do vendedor para cada pedido tem o teto na capacidade da equipe. "
                  "Aqui, como o cliente compra sozinho, o teto vira a experiência do portal e a disponibilidade do catálogo."),
        "pot_low": "R$ 50 mil", "pot_high": "R$ 250 mil",
        "deixa_mes": "R$ 4 mil a R$ 20 mil por mês",
        "pot_base": "Estimativa baseada em operação B2B digital com faturamento entre R$ 500 mil e R$ 1 milhão.",
        "significa": ("A Sharp está no perfil que mais se beneficia de um portal B2B com autoatendimento: "
                       "a demanda já existe, falta apenas o canal digital para capturá-la."),
        "erp": "Outro",
        "erp_integ": "Integração sob projeto",
        "erp_golive": "30 a 60 dias",
        "erp_dev": "Sim (projeto)",
        "erp_line": ("A integração será construída sob medida para o ERP desta operação. Prazo médio: 30 a 60 dias."),
        "pushpull": ("Operação com perfil puxado: o cliente JÁ compra sozinho. Basta estruturar o canal digital para capturar essa demanda."),
    },
    {
        "slug": "topcolors",
        "theme": "dark",
        "empresa": "TOP COLORS",
        "contato": "Tiago",
        "cargo_area": "Comunicação visual, decoração, estamparia digital",
        "local": "Brasil",
        "telefone": "(18) 3642-7184",
        "site": "facebook.com/topcolorsoficial",
        "sobre": ("Há cerca de 16 anos, em 2009/2010, nascia em Birigui-SP a Top Colors Company Ltda, "
                  "fruto da aposta de empreendedores locais no potencial da comunicação visual no interior paulista. "
                  "Estruturada como Ltda e com CNPJ ativo, a empresa consolidou-se ao longo de mais de uma década e meia "
                  "criando, produzindo e entregando soluções personalizadas em comunicação visual, decoração, "
                  "estamparia digital e adesivos. Hoje atende clientes do comércio, indústria e eventos da região de Birigui "
                  "e do noroeste paulista, combinando impressão digital de alta definição com acabamento e instalação próprios "
                  "— um parceiro consultivo para quem busca fortalecer marca e identidade visual."),
        "sobre_fonte": "Fonte: pesquisa web e respostas do diagnóstico comercial Zydon.",
        "vende_para": "clientes do comércio, indústria e eventos da região de Birigui e do noroeste paulista",
        "como_vende": "Comunicação visual, decoração, estamparia digital — modelo consultivo",
        "loja_virtual": "Não",
        "erp": "Bling",
        "vendedores": "1-3",
        "time_total": "2-5",
        "faturamento": "De R$1 milhão a R$5 milhões ao ano",
        "compra_sozinho": "Com ctza",
        "self_serve_resp": "sim",
        "dor": "pedidos chegam desorganizados (whatsapp, telefone, planilha)",
        "encontramos": [
            "Pedidos vindos de WhatsApp, telefone e planilha sem unificação",
            "Cliente já compra sozinho, mas ainda depende de vendedor para fechar",
            "ERP Bling em uso, mas sem portal digital conectado"
        ],
        "detalhe": "Hoje os pedidos da Top Colors chegam soltos — exigindo retrabalho manual a cada entrada.",
        "conta": ("Quem depende do vendedor para cada pedido tem o teto na capacidade da equipe. "
                  "Aqui, como o cliente compra sozinho, o teto vira a experiência do portal e a disponibilidade do catálogo."),
        "pot_low": "R$ 140 mil",
        "pot_high": "R$ 700 mil",
        "deixa_mes": "R$ 12 mil a R$ 58 mil",
        "pot_base": "14% aplicado sobre a faixa de faturamento informada (R$1–5 milhões).",
        "significa": ("A Top Colors está no perfil que mais se beneficia da digitalização: "
                       "operação puxada pelo cliente com ERP já em uso."),
        "erp": "Bling",
        "erp_integ": "Integração nativa",
        "erp_golive": "20 a 30 dias",
        "erp_dev": "Zero. Sem projeto de TI",
        "erp_line": "Integração nativa com o Bling: catálogo, preços e pedidos sincronizados automaticamente.",
        "pushpull": ("Operação puxada pelo cliente (pedidos de comunicação visual) — "
                      "o cliente quer comprar sozinho, e o portal B2B acelera isso."),
    },
]
